version: "3"

services:
  database:
    build:
      context: ./database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: memfault
    ports:
      - "5432:5432"